### ISSUE TITLE
In Section 8.4 guided exercise, https://www.chef.io/chef/install.sh url no longer exists and throws 301 moved permanently.

### ISSUE THREAD

**Issue by buraiden-masa** [RedHatTraining/DO288-apps#213]
The Nexus3 container's Dockerfile in section 8.4 downloads the shell script for its install from following url:
<pre>
RUN yum install -y --disableplugin=subscription-manager hostname procps \
    && curl -L https://www.chef.io/chef/install.sh | bash -s -- -v 14.12.9 \ <-----(*) See Here!
    && /opt/chef/embedded/bin/erb /var/chef/solo.json.erb > /var/chef/solo.json \
    && chef-solo \
       --recipe-url ${NEXUS_REPOSITORY_MANAGER_COOKBOOK_URL} \
       --json-attributes /var/chef/solo.json \
</pre>

But, it is no longer exists and has been moved to another location. This causes the podman build to fail.
<pre>
# curl -i https://www.chef.io/chef/install.sh
HTTP/1.1 301 Moved Permanently
  :

/* In my lab environment */
[student@workstation nexus3]$ podman build -t nexus3 .

   :
/bin/sh: /opt/chef/embedded/bin/erb: No such file or directory
Error: error building at STEP "RUN yum install -y … (snip)
</pre>

As described in the following document, it needs to download from another url.
https://docs.chef.io/chef_install_script/
<pre>
curl -L https://omnitruck.chef.io/install.sh | sudo bash
</pre>

**Comment by m-czernek** [comment]
Hi there @buraiden-masa ,

Nice to hear from you again! HTTP 301 means a redirect. That's why the curl uses the `-L` option. If you execute the following command, you will actually download the `install.sh` file:

```
curl -L https://www.chef.io/chef/install.sh -o install.sh
```

This suggests to me that the URL in the Containerifle is correct. I have tried building the container and have succeeded on my local machine. 

However, I'd like to bring your attention to a PR we have made recently. In https://github.com/RedHatTraining/DO288-apps/pull/192, we have fixed the link.

I have noticed that in your personal fork, it seems you have reverted this commit, i.e. https://github.com/mohashi-rh/DO288-apps/commit/c83c244b73c0441caf8ef275409866bbeca02cc2. If you use the `getchef.io` URL, that is indeed incorrect. We have fixed that in our fork.

If that is the case, your changes to your fork actually undid our changes, which would result in a failing build.

Note that the support you receive here is a best-effort support from the developers of the course, customers can always request Red Hat support by using the `support` button in ROL.

![image](https://user-images.githubusercontent.com/16302538/154276415-5883859f-0fb7-4f8a-84e0-330e8026b2dc.png)

**Comment by buraiden-masa** [comment]
Hello @m-czernek ,

Thank you for your reply !
I rechecked my nexus3 container's Dockerfile in labs, and certainly  there is a URL miss configure.
<pre>
RUN yum install -y --disableplugin=subscription-manager hostname procps \
    && curl -L https://www.getchef.com/chef/install.sh | bash -s -- -v 14.12.9 \ <----(*)
</pre>

As you said, curl -L does the redirect. However, it seems the URL itself was wrong in the first place ...
Therefore, I would like to clone and recreate my DO288 files. Thank you !

Regards,
